
default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["BACKEND_DATABASE_PORT"] %>
  pool: 5
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["BACKEND_DATABASE_HOST"] %>
  database: <%= ENV["BACKEND_DATABASE_NAME"] %>
  username: <%= ENV["BACKEND_DATABASE_USERNAME"] %>
  password:

test:
  <<: *default
  database: backend_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["BACKEND_DATABASE_HOST"] %>
    database: <%= ENV["BACKEND_DATABASE"] %>
    username: <%= ENV["BACKEND_DATABASE_USERNAME"] %>
    password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_production_cable
    migrations_paths: db/cable_migrate
