name: CD - Deploy to Production

on:
  push:
    branches: ["main"]

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 187.127.1.143 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 deploy@187.127.1.143 "echo SUCCESS"

      - name: Deploy using Capistrano
        run: bundle exec cap production deploy